# Generated by Django 4.2.19 on 2025-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gastos_data_alter_gastos_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
